version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - dev-network

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/books
      - ME_CONFIG_BASICAUTH_USERNAME=secret
      - ME_CONFIG_BASICAUTH_PASSWORD=secret
    networks:
      - dev-network
    ports:
      - "8081:8081"

volumes:
  mongo-data:

networks:
  dev-network:
    driver: bridge
